config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  resources :booking_histories
  resources :users
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking_history.rb
class BookingHistory < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :booking_histories
    has_many :users, through: :booking_histories
end

app/models/user.rb
class User < ApplicationRecord
    has_many :booking_histories
    has_many :rooms, through: :booking_histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_histories_controller.rb
class BookingHistoriesController < ApplicationController
  before_action :set_booking_history, only: %i[ show edit update destroy ]

  # GET /booking_histories or /booking_histories.json
  def index
    @booking_histories = BookingHistory.all
  end

  # GET /booking_histories/1 or /booking_histories/1.json
  def show
  end

  # GET /booking_histories/new
  def new
    @booking_history = BookingHistory.new
  end

  # GET /booking_histories/1/edit
  def edit
  end

  # POST /booking_histories or /booking_histories.json
  def create
    @booking_history = BookingHistory.new(booking_history_params)
    @booking_history.room.update(isAvailable: false)

    respond_to do |format|
      if @booking_history.save
        format.html { redirect_to booking_history_url(@booking_history), notice: "Booking history was successfully created." }
        format.json { render :show, status: :created, location: @booking_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_histories/1 or /booking_histories/1.json
  def update
    respond_to do |format|
      if @booking_history.update(booking_history_params)
        format.html { redirect_to booking_history_url(@booking_history), notice: "Booking history was successfully updated." }
        format.json { render :show, status: :ok, location: @booking_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_histories/1 or /booking_histories/1.json
  def destroy
    @booking_history.destroy

    respond_to do |format|
      format.html { redirect_to booking_histories_url, notice: "Booking history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_history
      @booking_history = BookingHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_history_params
      params.require(:booking_history).permit(:user_id, :room_id, :checkIn, :checkOut, :description)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:bedNum, :price, :description, :isAvailable)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone, :description, :isAdmin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_histories_helper.rb
module BookingHistoriesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/booking_histories/_booking_history.html.erb
<div id="<%= dom_id booking_history %>">
  <p>
    <strong>User:</strong>
    <%= booking_history.user_id %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= booking_history.room_id %>
  </p>

  <p>
    <strong>Checkin:</strong>
    <%= booking_history.checkIn %>
  </p>

  <p>
    <strong>Checkout:</strong>
    <%= booking_history.checkOut %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= booking_history.description %>
  </p>

</div>

app/views/booking_histories/_form.html.erb
<%= form_with(model: booking_history) do |form| %>
  <% if booking_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking_history.errors.count, "error") %> prohibited this booking_history from being saved:</h2>

      <ul>
        <% booking_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.all, :id, :name %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.collection_select :room_id, Room.where(isAvailable: true), :id, :id %>
  </div>

  <div>
    <%= form.label :checkIn, style: "display: block" %>
    <%= form.date_field :checkIn %>
  </div>

  <div>
    <%= form.label :checkOut, style: "display: block" %>
    <%= form.date_field :checkOut %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/booking_histories/edit.html.erb
<h1>Editing booking history</h1>

<%= render "form", booking_history: @booking_history %>

<br>

<div>
  <%= link_to "Show this booking history", @booking_history %> |
  <%= link_to "Back to booking histories", booking_histories_path %>
</div>

app/views/booking_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Booking histories</h1>

<div id="booking_histories">
  <% @booking_histories.each do |booking_history| %>
    <%= render booking_history %>
    <p>
      <%= link_to "Show this booking history", booking_history %>
    </p>
  <% end %>
</div>

<%= link_to "New booking history", new_booking_history_path %>

app/views/booking_histories/new.html.erb
<h1>New booking history</h1>

<%= render "form", booking_history: @booking_history %>

<br>

<div>
  <%= link_to "Back to booking histories", booking_histories_path %>
</div>

app/views/booking_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking_history %>

<div>
  <%= link_to "Edit this booking history", edit_booking_history_path(@booking_history) %> |
  <%= link_to "Back to booking histories", booking_histories_path %>

  <%= button_to "Destroy this booking history", @booking_history, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelManagementV1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bedNum, style: "display: block" %>
    <%= form.number_field :bedNum %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :isAvailable, style: "display: block" %>
    <%= form.check_box :isAvailable %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Bednum:</strong>
    <%= room.bedNum %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= room.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= room.description %>
  </p>

  <p>
    <strong>Isavailable:</strong>
    <%= room.isAvailable %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :isAdmin, style: "display: block" %>
    <%= form.check_box :isAdmin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= user.description %>
  </p>

  <p>
    <strong>Isadmin:</strong>
    <%= user.isAdmin %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>